version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X github.com/PapaDanielVi/ostrakon/cmd/ostrakon/commands.Version={{ .Tag }}"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

homebrew_casks:
  - repository:
      owner: PapaDanielVi
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

    directory: Formula

    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    binaries:
      - ostrakon
      - ostra

    homepage: "https://github.com/PapaDanielVi/ostrakon"
    description: "Ostrakon is a secure CLI tool for managing secrets in a private GitHub repository with client-side encryption."
    license: "MIT"
