// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/PapaDanielVi/ostrakon/pkg/vault (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=pkg/mocks/mock_vault.go github.com/PapaDanielVi/ostrakon/pkg/vault Provider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vault "github.com/PapaDanielVi/ostrakon/pkg/vault"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// CheckConnectivity mocks base method.
func (m *MockProvider) CheckConnectivity(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckConnectivity", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckConnectivity indicates an expected call of CheckConnectivity.
func (mr *MockProviderMockRecorder) CheckConnectivity(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckConnectivity", reflect.TypeOf((*MockProvider)(nil).CheckConnectivity), ctx)
}

// DeleteFile mocks base method.
func (m *MockProvider) DeleteFile(ctx context.Context, path, sha, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, path, sha, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockProviderMockRecorder) DeleteFile(ctx, path, sha, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockProvider)(nil).DeleteFile), ctx, path, sha, message)
}

// DownloadFile mocks base method.
func (m *MockProvider) DownloadFile(ctx context.Context, path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockProviderMockRecorder) DownloadFile(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockProvider)(nil).DownloadFile), ctx, path)
}

// GetFileSHA mocks base method.
func (m *MockProvider) GetFileSHA(ctx context.Context, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileSHA", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileSHA indicates an expected call of GetFileSHA.
func (mr *MockProviderMockRecorder) GetFileSHA(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileSHA", reflect.TypeOf((*MockProvider)(nil).GetFileSHA), ctx, path)
}

// ListFiles mocks base method.
func (m *MockProvider) ListFiles(ctx context.Context) ([]vault.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiles", ctx)
	ret0, _ := ret[0].([]vault.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockProviderMockRecorder) ListFiles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiles", reflect.TypeOf((*MockProvider)(nil).ListFiles), ctx)
}

// Owner mocks base method.
func (m *MockProvider) Owner() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Owner")
	ret0, _ := ret[0].(string)
	return ret0
}

// Owner indicates an expected call of Owner.
func (mr *MockProviderMockRecorder) Owner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Owner", reflect.TypeOf((*MockProvider)(nil).Owner))
}

// Repo mocks base method.
func (m *MockProvider) Repo() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Repo")
	ret0, _ := ret[0].(string)
	return ret0
}

// Repo indicates an expected call of Repo.
func (mr *MockProviderMockRecorder) Repo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Repo", reflect.TypeOf((*MockProvider)(nil).Repo))
}

// RepoURL mocks base method.
func (m *MockProvider) RepoURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// RepoURL indicates an expected call of RepoURL.
func (mr *MockProviderMockRecorder) RepoURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoURL", reflect.TypeOf((*MockProvider)(nil).RepoURL))
}

// UploadFile mocks base method.
func (m *MockProvider) UploadFile(ctx context.Context, path string, content []byte, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, path, content, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockProviderMockRecorder) UploadFile(ctx, path, content, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockProvider)(nil).UploadFile), ctx, path, content, message)
}
